name: Continuous Integration
on:
  workflow_run:
    workflows: ["tests workflow"]  
    types: [completed]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push http-backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/http-backend/Dockerfile
          push: true
          tags: |
            sumit487/chatapp-httpbackend:${{ github.sha }}
            sumit487/chatapp-httpbackend:latest

      
      - name: Build and push wssbackend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/wsbackend/Dockerfile
          push: true
          tags: |
            sumit487/chatapp-wssbackend:${{ github.sha }}
            sumit487/chatapp-wssbackend:latest
      
      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/web/Dockerfile
          push: true
          tags: |
            sumit487/chatapp-frontend:${{ github.sha }}
            sumit487/chatapp-frontend:latest
          build-args: |
            NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}
            NEXT_PUBLIC_WEBSOCKET_BACKEND_URL=${{ secrets.NEXT_PUBLIC_WEBSOCKET_BACKEND_URL }}
  
  deploy:
    needs: build-and-push   
    runs-on: ubuntu-latest


    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}

    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/chatapp
            sudo docker compose -f docker-compose.yaml pull
            sudo docker compose --env-file .env -f docker-compose.yaml up -d --remove-orphans
            sudo docker system prune -f
  
